name: Node.js CI/CD

on:
  push:
    branches: [ "newBranch" ]
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Install pm2 globally
    - run: npm install -g pm2

    # SSH into the EC2 instance and deploy
    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ec2-51-21-131-184.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure the private key is added to GitHub Secrets
        script: |
          cd ~/hisaabkaro
          git pull origin newBranch
          pm2 restart all
    # Set environment variables on the server (only if .env doesn't already exist)
    - name: Ensure .env file is not modified
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ec2-51-21-131-184.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/hisaabkaro
          if [ ! -f ".env" ]; then
            touch .env
            echo "${{ secrets.CRM_ENV_FILE }}" > .env
          else
            echo ".env file already exists, skipping update."
          fi