name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Install pm2 globally
    - run: npm install -g pm2

    # SSH into the EC2 instance and deploy
    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ec2-51-21-131-184.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to project directory
          cd ~/hisaabkaro
          
          # Stop the application
          pm2 stop all
          
          # Backup current build
          timestamp=$(date +%Y%m%d_%H%M%S)
          if [ -d "build" ]; then
            mv build "build_backup_$timestamp"
          fi
          
          # Pull latest changes
          git pull origin main
          
          # Install backend dependencies
          npm ci
          
          # Navigate to frontend directory
          cd khatabookfrontend
          
          # Install frontend dependencies and build
          npm ci
          REACT_APP_URL="https://hisaabkaro.com" npm run build
          
          # Move build to backend and ensure permissions
          cd ..
          mv khatabookfrontend/build .
          chmod -R 755 build
          
          # Verify build directory
          if [ ! -d "build" ] || [ ! -f "build/index.html" ]; then
            echo "Build directory is missing or incomplete"
            # Restore backup if available
            if [ -d "build_backup_$timestamp" ]; then
              rm -rf build
              mv "build_backup_$timestamp" build
            fi
            exit 1
          fi
          
          # Start the application
          pm2 start all
          
          # Verify application status
          sleep 5
          pm2 list
          
          # Clean old backups (keep last 5)
          ls -dt build_backup_* | tail -n +6 | xargs -r rm -rf

    # Set environment variables
    - name: Setup environment
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ec2-51-21-131-184.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/hisaabkaro
          if [ ! -f ".env" ]; then
            touch .env
            echo "${{ secrets.CRM_ENV_FILE }}" > .env
          fi
